import { listStoredGoogleAccounts } from "@/lib/account-store"
import { fetchGmailDrafts } from "@/lib/google-auth"

export default async function DraftsPage() {
  const accounts = await listStoredGoogleAccounts()

  if (!accounts.length) {
    return (
      <main className="container flex flex-col gap-6 pb-12 pt-10">
        <h1 className="text-2xl font-semibold text-foreground">Drafts</h1>
        <p className="text-sm text-muted-foreground">
          Connect a Gmail account to view drafts created by InboxerAI.
        </p>
      </main>
    )
  }

  const account = accounts[0]

  const drafts = await fetchGmailDrafts(account.tokens, 20)

  return (
    <main className="container flex flex-col gap-6 pb-12 pt-10">
      <header className="space-y-1">
        <h1 className="text-2xl font-semibold text-foreground">Drafts</h1>
        <p className="text-sm text-muted-foreground">
          Showing Gmail drafts generated by InboxerAI for {account.email}.
        </p>
      </header>

      {drafts.length ? (
        <ul className="grid gap-3">
          {drafts.map((draft) => (
            <li
              key={draft.id}
              className="rounded-lg border border-border bg-card/80 p-4 shadow-sm"
            >
              <div className="flex flex-col gap-1 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between">
                <span>
                  Thread:{" "}
                  <span className="font-medium text-foreground">
                    {draft.threadId ?? "Unknown"}
                  </span>
                </span>
                <span>
                  Created {formatTimestamp(draft.message.date)}
                </span>
              </div>
              <p className="mt-2 text-sm font-semibold text-foreground">
                {draft.message.subject}
              </p>
              <p className="text-xs text-muted-foreground">
                To: {draft.message.to}
              </p>
              <div className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-foreground">
                {draft.message.bodyText || "Draft body is empty."}
              </div>
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-sm text-muted-foreground">
          No Gmail drafts were found. When InboxerAI processes incoming mail it
          will create drafts automatically and they will appear here.
        </p>
      )}
    </main>
  )
}

function formatTimestamp(value?: string) {
  if (!value) {
    return "unknown time"
  }
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }
  return date.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  })
}
